### ISSUE TITLE
Add Spring Cloud Gateway

### ISSUE THREAD

**Issue by abitgen** [abitgen/spring-cloud-start#2]
Use `org.springframework.cloud:spring-cloud-starter-gateway` dependency instead of Zuul, and configure the property 

```
cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          predicates:
          - name: Path
            args:
              pattern: "'/'+serviceId+'/**'"
```
