### ISSUE TITLE
Add Spring Cloud Config server, Get properties from filesystem

### ISSUE THREAD

**Issue by abitgen** [abitgen/spring-cloud-start#4]

**Comment by abitgen** [comment]
Add following properties

```
spring:
  application:
    name: configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:I:\Workspace\Intellij\Spring\spring-cloud-start\config-server-file\src\main\resources\config
```


You can access the required properties using this url

`http://<CONFIG_SERVER_IP:PORT>/<CONFIG_SERVER_APPLICATION_NAME>/<PROFILE>`

Eg: `http://localhost:8601/configServer/default`
