### ISSUE TITLE
Refresh properties on All Microservices When Properties is updated in config server, using Spring cloud bus

### ISSUE THREAD

**Issue by abitgen** [abitgen/spring-cloud-start#5]

**Comment by abitgen** [comment]
Tried this https://www.baeldung.com/spring-cloud-bus, but no luck for now.

**Comment by abitgen** [comment]
Steps worked:
1. Add actuator, bus-amqp to config server application
2. add in properties

```
management:
  endpoints:
    web:
      exposure:
        include: 
          - bus-refresh
```
3. Add actuator, bus-amqp dependency to all other config consuming services, annotate main class with RefreshScope
4. Make a change to properties file in config git repo and push to git
5. POST to localhost:8601/actuator/bus-refresh
6. You should now see updated value.
